import {
  Skull,
  Flame,
  Zap,
  Snowflake,
  Crown,
  Sparkles,
  Sun,
  Moon,
  Star,
  Sword,
  Eye,
  Heart,
  Diamond,
  Target,
  Tornado,
  Waves,
} from "lucide-react";

export const colorThemes = [
  // DARK MODE THEMES (15 themes)
  {
    id: "brutal-red-dark",
    name: "💀 BRUTAL RED DEATH",
    mode: "dark",
    icon: Skull,
    primary: "from-red-600 to-red-800",
    secondary: "from-red-700 to-red-900",
    accent: "bg-red-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-red-500",
    description: "CLASSIC DESTRUCTION - DARK EDITION",
    category: "DARK",
  },
  {
    id: "toxic-green-dark",
    name: "🧪 TOXIC WASTE DARK",
    mode: "dark",
    icon: Flame,
    primary: "from-green-600 to-emerald-700",
    secondary: "from-green-700 to-emerald-800",
    accent: "bg-lime-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-green-500",
    description: "TOXIC MAYHEM IN THE SHADOWS",
    category: "DARK",
  },
  {
    id: "electric-purple-dark",
    name: "⚡ ELECTRIC NIGHTMARE",
    mode: "dark",
    icon: Zap,
    primary: "from-purple-600 to-violet-700",
    secondary: "from-purple-700 to-violet-800",
    accent: "bg-cyan-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-purple-500",
    description: "ELECTRIC FURY FROM THE VOID",
    category: "DARK",
  },
  {
    id: "ocean-chaos-dark",
    name: "🌊 DEEP SEA CHAOS",
    mode: "dark",
    icon: Waves,
    primary: "from-blue-600 to-cyan-700",
    secondary: "from-blue-700 to-cyan-800",
    accent: "bg-yellow-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-blue-500",
    description: "LIQUID VIOLENCE IN DARKNESS",
    category: "DARK",
  },
  {
    id: "golden-mayhem-dark",
    name: "👑 GOLDEN SHADOW",
    mode: "dark",
    icon: Crown,
    primary: "from-yellow-600 to-amber-700",
    secondary: "from-yellow-700 to-amber-800",
    accent: "bg-yellow-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-yellow-500",
    description: "ROYAL DESTRUCTION IN THE DARK",
    category: "DARK",
  },
  {
    id: "void-black-dark",
    name: "🖤 ENDLESS VOID",
    mode: "dark",
    icon: Skull,
    primary: "from-gray-700 to-black",
    secondary: "from-gray-800 to-gray-900",
    accent: "bg-white",
    background: "bg-black",
    surface: "bg-gray-900",
    text: "text-white",
    textSecondary: "text-gray-400",
    border: "border-gray-600",
    description: "PURE DARKNESS INCARNATE",
    category: "DARK",
  },
  {
    id: "cyber-neon-dark",
    name: "🤖 CYBERPUNK DARK",
    mode: "dark",
    icon: Zap,
    primary: "from-cyan-600 to-purple-700",
    secondary: "from-cyan-700 to-purple-800",
    accent: "bg-lime-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-cyan-500",
    description: "DIGITAL DESTRUCTION IN THE MATRIX",
    category: "DARK",
  },
  {
    id: "sunset-rage-dark",
    name: "🌅 TWILIGHT TERROR",
    mode: "dark",
    icon: Flame,
    primary: "from-pink-600 to-orange-700",
    secondary: "from-pink-700 to-orange-800",
    accent: "bg-yellow-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-pink-500",
    description: "SUNSET FURY IN THE ABYSS",
    category: "DARK",
  },
  {
    id: "blood-moon-dark",
    name: "🌙 BLOOD MOON RITUAL",
    mode: "dark",
    icon: Moon,
    primary: "from-red-800 to-purple-900",
    secondary: "from-red-900 to-purple-800",
    accent: "bg-red-300",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-red-700",
    description: "LUNAR BRUTALITY AT ITS PEAK",
    category: "DARK",
  },
  {
    id: "shadow-steel-dark",
    name: "⚔️ SHADOW STEEL",
    mode: "dark",
    icon: Sword,
    primary: "from-gray-600 to-slate-800",
    secondary: "from-gray-700 to-slate-900",
    accent: "bg-blue-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-gray-500",
    description: "FORGED IN DARKNESS AND STEEL",
    category: "DARK",
  },
  {
    id: "cosmic-terror-dark",
    name: "🌌 COSMIC TERROR",
    mode: "dark",
    icon: Star,
    primary: "from-indigo-700 to-purple-800",
    secondary: "from-indigo-800 to-purple-900",
    accent: "bg-pink-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-indigo-500",
    description: "INFINITE CHAOS FROM THE COSMOS",
    category: "DARK",
  },
  {
    id: "neon-hazard-dark",
    name: "☢️ NEON HAZARD",
    mode: "dark",
    icon: Zap,
    primary: "from-lime-600 to-yellow-700",
    secondary: "from-lime-700 to-yellow-800",
    accent: "bg-black",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-lime-500",
    description: "RADIOACTIVE BRUTALITY UNLEASHED",
    category: "DARK",
  },
  {
    id: "crimson-edge-dark",
    name: "🗡️ CRIMSON EDGE",
    mode: "dark",
    icon: Target,
    primary: "from-red-700 to-black",
    secondary: "from-red-800 to-gray-900",
    accent: "bg-red-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-red-600",
    description: "SHARP AS A BLADE, DARK AS NIGHT",
    category: "DARK",
  },
  {
    id: "phantom-violet-dark",
    name: "👻 PHANTOM VIOLET",
    mode: "dark",
    icon: Eye,
    primary: "from-violet-700 to-purple-800",
    secondary: "from-violet-800 to-purple-900",
    accent: "bg-white",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-violet-500",
    description: "SPECTRAL BRUTALITY FROM BEYOND",
    category: "DARK",
  },
  {
    id: "obsidian-storm-dark",
    name: "🌪️ OBSIDIAN STORM",
    mode: "dark",
    icon: Tornado,
    primary: "from-slate-700 to-black",
    secondary: "from-slate-800 to-gray-900",
    accent: "bg-blue-400",
    background: "bg-gray-900",
    surface: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    border: "border-slate-500",
    description: "VOLCANIC GLASS MEETS TORNADO FURY",
    category: "DARK",
  },

  // LIGHT MODE THEMES (15 themes)
  {
    id: "brutal-red-light",
    name: "🔥 BRUTAL RED INFERNO",
    mode: "light",
    icon: Flame,
    primary: "from-red-400 to-red-600",
    secondary: "from-red-500 to-red-700",
    accent: "bg-red-600",
    background: "bg-red-50",
    surface: "bg-white",
    text: "text-red-900",
    textSecondary: "text-red-700",
    border: "border-red-300",
    description: "BLAZING DESTRUCTION IN DAYLIGHT",
    category: "LIGHT",
  },
  {
    id: "toxic-green-light",
    name: "🌿 TOXIC NEON LIGHT",
    mode: "light",
    icon: Sparkles,
    primary: "from-green-400 to-emerald-500",
    secondary: "from-green-500 to-emerald-600",
    accent: "bg-green-600",
    background: "bg-green-50",
    surface: "bg-white",
    text: "text-green-900",
    textSecondary: "text-green-700",
    border: "border-green-300",
    description: "TOXIC ENERGY IN THE LIGHT",
    category: "LIGHT",
  },
  {
    id: "electric-purple-light",
    name: "⚡ ELECTRIC SUNSHINE",
    mode: "light",
    icon: Zap,
    primary: "from-purple-400 to-violet-500",
    secondary: "from-purple-500 to-violet-600",
    accent: "bg-purple-600",
    background: "bg-purple-50",
    surface: "bg-white",
    text: "text-purple-900",
    textSecondary: "text-purple-700",
    border: "border-purple-300",
    description: "ELECTRIC FURY IN BRIGHT LIGHT",
    category: "LIGHT",
  },
  {
    id: "ocean-chaos-light",
    name: "🌊 CRYSTAL OCEAN",
    mode: "light",
    icon: Waves,
    primary: "from-blue-400 to-cyan-500",
    secondary: "from-blue-500 to-cyan-600",
    accent: "bg-blue-600",
    background: "bg-blue-50",
    surface: "bg-white",
    text: "text-blue-900",
    textSecondary: "text-blue-700",
    border: "border-blue-300",
    description: "LIQUID VIOLENCE IN CRYSTAL CLEAR",
    category: "LIGHT",
  },
  {
    id: "golden-mayhem-light",
    name: "👑 GOLDEN DAYLIGHT",
    mode: "light",
    icon: Crown,
    primary: "from-yellow-400 to-amber-500",
    secondary: "from-yellow-500 to-amber-600",
    accent: "bg-yellow-600",
    background: "bg-yellow-50",
    surface: "bg-white",
    text: "text-yellow-900",
    textSecondary: "text-yellow-700",
    border: "border-yellow-300",
    description: "ROYAL DESTRUCTION IN GOLDEN LIGHT",
    category: "LIGHT",
  },
  {
    id: "void-light",
    name: "🤍 PURE LIGHT VOID",
    mode: "light",
    icon: Sun,
    primary: "from-gray-200 to-gray-400",
    secondary: "from-gray-300 to-gray-500",
    accent: "bg-gray-700",
    background: "bg-gray-50",
    surface: "bg-white",
    text: "text-gray-900",
    textSecondary: "text-gray-600",
    border: "border-gray-300",
    description: "MINIMALIST DESTRUCTION",
    category: "LIGHT",
  },
  {
    id: "cyber-neon-light",
    name: "🤖 CYBER BRIGHT",
    mode: "light",
    icon: Zap,
    primary: "from-cyan-400 to-purple-500",
    secondary: "from-cyan-500 to-purple-600",
    accent: "bg-cyan-600",
    background: "bg-cyan-50",
    surface: "bg-white",
    text: "text-cyan-900",
    textSecondary: "text-cyan-700",
    border: "border-cyan-300",
    description: "DIGITAL DESTRUCTION IN NEON LIGHT",
    category: "LIGHT",
  },
  {
    id: "sunset-rage-light",
    name: "🌅 DAWN DESTRUCTION",
    mode: "light",
    icon: Flame,
    primary: "from-pink-400 to-orange-500",
    secondary: "from-pink-500 to-orange-600",
    accent: "bg-pink-600",
    background: "bg-pink-50",
    surface: "bg-white",
    text: "text-pink-900",
    textSecondary: "text-pink-700",
    border: "border-pink-300",
    description: "SUNRISE FURY IN FULL GLORY",
    category: "LIGHT",
  },
  {
    id: "mint-destruction-light",
    name: "🌿 MINT CHAOS LIGHT",
    mode: "light",
    icon: Sparkles,
    primary: "from-emerald-300 to-teal-400",
    secondary: "from-emerald-400 to-teal-500",
    accent: "bg-emerald-600",
    background: "bg-emerald-50",
    surface: "bg-white",
    text: "text-emerald-900",
    textSecondary: "text-emerald-700",
    border: "border-emerald-300",
    description: "FRESH VIOLENCE IN DAYLIGHT",
    category: "LIGHT",
  },
  {
    id: "brutal-orange-light",
    name: "🔥 ORANGE INFERNO",
    mode: "light",
    icon: Flame,
    primary: "from-orange-400 to-red-500",
    secondary: "from-orange-500 to-red-600",
    accent: "bg-orange-600",
    background: "bg-orange-50",
    surface: "bg-white",
    text: "text-orange-900",
    textSecondary: "text-orange-700",
    border: "border-orange-300",
    description: "BLAZING CHAOS IN BRIGHT LIGHT",
    category: "LIGHT",
  },
  {
    id: "solar-flare-light",
    name: "☀️ SOLAR FLARE",
    mode: "light",
    icon: Sun,
    primary: "from-yellow-300 to-orange-400",
    secondary: "from-yellow-400 to-orange-500",
    accent: "bg-red-600",
    background: "bg-yellow-50",
    surface: "bg-white",
    text: "text-yellow-900",
    textSecondary: "text-yellow-700",
    border: "border-yellow-300",
    description: "NUCLEAR FUSION IN DAYLIGHT",
    category: "LIGHT",
  },
  {
    id: "crystal-blade-light",
    name: "💎 CRYSTAL BLADE",
    mode: "light",
    icon: Diamond,
    primary: "from-slate-300 to-blue-400",
    secondary: "from-slate-400 to-blue-500",
    accent: "bg-blue-600",
    background: "bg-slate-50",
    surface: "bg-white",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    border: "border-slate-300",
    description: "SHARP AS DIAMOND, CLEAR AS CRYSTAL",
    category: "LIGHT",
  },
  {
    id: "cherry-bomb-light",
    name: "🍒 CHERRY BOMB",
    mode: "light",
    icon: Heart,
    primary: "from-pink-300 to-red-400",
    secondary: "from-pink-400 to-red-500",
    accent: "bg-red-600",
    background: "bg-pink-50",
    surface: "bg-white",
    text: "text-pink-900",
    textSecondary: "text-pink-700",
    border: "border-pink-300",
    description: "SWEET DESTRUCTION WITH A BANG",
    category: "LIGHT",
  },
  {
    id: "neon-lime-light",
    name: "🟢 NEON LIME ASSAULT",
    mode: "light",
    icon: Zap,
    primary: "from-lime-300 to-green-400",
    secondary: "from-lime-400 to-green-500",
    accent: "bg-black",
    background: "bg-lime-50",
    surface: "bg-white",
    text: "text-lime-900",
    textSecondary: "text-lime-700",
    border: "border-lime-300",
    description: "ACIDIC BRIGHTNESS BURNS THE EYES",
    category: "LIGHT",
  },
  {
    id: "arctic-storm-light",
    name: "❄️ ARCTIC STORM",
    mode: "light",
    icon: Snowflake,
    primary: "from-blue-300 to-cyan-400",
    secondary: "from-blue-400 to-cyan-500",
    accent: "bg-blue-600",
    background: "bg-blue-50",
    surface: "bg-white",
    text: "text-blue-900",
    textSecondary: "text-blue-700",
    border: "border-blue-300",
    description: "FROZEN FURY IN CRYSTALLINE FORM",
    category: "LIGHT",
  },
] as const;

export const themeCategories = ["ALL", "DARK", "LIGHT"] as const;

export type ColorTheme = (typeof colorThemes)[number];
export type ThemeMode = "dark" | "light";
export type ThemeCategory = "DARK" | "LIGHT";
